
spring:
  application:
    name: portfolio-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Ff6136581
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
