spring:
  application:
    name: devBrain-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  main:
    lazy-initialization: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small

    vectorstore:
      qdrant:
        url: https://e80f5f2c-8892-4af2-a3ff-6d04da7df7db.sa-east-1-0.aws.cloud.qdrant.io
        api-key: ${SPRING_AI_VECTORSTORE_QDRANT_API_KEY}
        collection-name: portfolio_docs
        initialize-schema: false

server:
  port: ${SERVER_PORT:8080}

app:
  rag:
    enabled: true
  library:
    github:
      owner: houdajh
      repo: rag-data
      branch: master
      base-path: library
      token: ${GITHUB_TOKEN}
